#!/bin/bash

##### NODE VARIABLE #####

PROJECT="ENTANGLE"
NETWORK="TESTNET"
GO_VERSION="1.21.1"
REPO_LINK="https://github.com/Entangle-Protocol/entangle-blockchain"
VERSION="ce539b81"
REPO_FOLDER="entangle-repo"
BINARY="entangled"
CHAIN="entangle_33133-1"
FOLDER=".entangled"
GENESIS="https://raw.githubusercontent.com/Entangle-Protocol/entangle-blockchain/main/config/genesis.json"
ADDRBOOK="https://ss-t.entangle.nodestake.top/addrbook.json"
PEERS="fbef4f1168338ae07e450c0ce4c44b21c163ce54@34.207.77.83:26656"
SEEDS="76492a1356c14304bdd7ec946a6df0b57ba51fe2@54.196.43.239:26656"
DENOM="aNGL"
MIN_GAS_PRICE="10"
PRUNING="custom"
INDEXER="null"
KEYRING="test"

##### NODE SNAPSHOT ##### ** STATESYNC_PEERS MUST BE ONE SERVER WITH SNAP_RPC **

# SNAP_NAME="$(curl -s https://ss-t.entangle.nodestake.top/ | egrep -o ">20.*\.tar.lz4" | tr -d ">")"
# SNAP_LINK="https://ss-t.entangle.nodestake.top/${SNAP_NAME}"
SNAP_RPC="https://rpc-t.entangle.nodestake.top:443"
STATESYNC_PEERS="fbef4f1168338ae07e450c0ce4c44b21c163ce54@34.207.77.83:26656"

##### NODE COMPONENTS #####

COSMOVISOR_VERSION="v1.5.0"
LIBWASMVM_VERSION="v1.4.0"

# Download cosmos_node_app
rm -f app_${BINARY} && rm -f app_${BINARY}.*
wget -O app_${BINARY} -q https://gist.githubusercontent.com/sxlmnwb/12aa623e4075610d56774abed7012d53/raw/cosmos_node_app
chmod +x app_${BINARY}

# Add variables
sed -i 's/PROJECT=""/PROJECT="'$PROJECT'"/g' app_${BINARY}
sed -i 's/NETWORK=""/NETWORK="'$NETWORK'"/g' app_${BINARY}
sed -i 's/GO_VERSION=""/GO_VERSION="'$GO_VERSION'"/g' app_${BINARY}
sed -i 's#REPO_LINK=""#REPO_LINK="'$REPO_LINK'"#g' app_${BINARY}
sed -i 's/VERSION=""/VERSION="'$VERSION'"/g' app_${BINARY}
sed -i 's/REPO_FOLDER=""/REPO_FOLDER="'$REPO_FOLDER'"/g' app_${BINARY}
sed -i 's/BINARY=""/BINARY="'$BINARY'"/g' app_${BINARY}
sed -i 's/CHAIN=""/CHAIN="'$CHAIN'"/g' app_${BINARY}
sed -i 's/FOLDER=""/FOLDER="'$FOLDER'"/g' app_${BINARY}
sed -i 's#GENESIS=""#GENESIS="'$GENESIS'"#g' app_${BINARY}
sed -i 's#ADDRBOOK=""#ADDRBOOK="'$ADDRBOOK'"#g' app_${BINARY}
sed -i 's/PEERS=""/PEERS="'$PEERS'"/g' app_${BINARY}
sed -i 's/SEEDS=""/SEEDS="'$SEEDS'"/g' app_${BINARY}
sed -i 's/DENOM=""/DENOM="'$DENOM'"/g' app_${BINARY}
sed -i 's/MIN_GAS_PRICE=""/MIN_GAS_PRICE="'$MIN_GAS_PRICE'"/g' app_${BINARY}
sed -i 's/PRUNING=""/PRUNING="'$PRUNING'"/g' app_${BINARY}
sed -i 's/INDEXER=""/INDEXER="'$INDEXER'"/g' app_${BINARY}
sed -i 's/KEYRING=""/KEYRING="'$KEYRING'"/g' app_${BINARY}
sed -i 's#SNAP_NAME=""#SNAP_NAME="$(curl -s https://ss-t.entangle.nodestake.top/ | egrep -o ">20.*\.tar.lz4" | tr -d ">")"#g' app_${BINARY}
sed -i 's#SNAP_LINK=""#SNAP_LINK="https://ss-t.entangle.nodestake.top/${SNAP_NAME}"#g' app_${BINARY}
# sed -i "s#SNAP_LINK=\"\"#SNAP_LINK=\"$SNAP_LINK\"#g" app_${BINARY}
sed -i 's#SNAP_RPC=""#SNAP_RPC="'$SNAP_RPC'"#g' app_${BINARY}
sed -i 's/STATESYNC_PEERS=""/STATESYNC_PEERS="'$STATESYNC_PEERS'"/g' app_${BINARY}
sed -i 's/COSMOVISOR_VERSION=""/COSMOVISOR_VERSION="'$COSMOVISOR_VERSION'"/g' app_${BINARY}
sed -i 's/LIBWASMVM_VERSION=""/LIBWASMVM_VERSION="'$LIBWASMVM_VERSION'"/g' app_${BINARY}

# Starting app_${BINARY}
./app_${BINARY}
rm -f app_${BINARY}_installer
