#!/bin/bash

##### NODE VARIABLE #####

PROJECT="DYMENSION"
NETWORK="TESTNET"
GO_VERSION="1.21.1"
REPO_LINK="https://github.com/dymensionxyz/dymension"
VERSION="v1.0.2-beta"
REPO_FOLDER="dymension-repo"
BINARY="dymd"
CHAIN="froopyland_100-1"
FOLDER=".dymension"
GENESIS="https://github.com/dymensionxyz/testnets/raw/main/dymension-hub/froopyland/genesis.json"
ADDRBOOK="https://snapshots.kjnodes.com/dymension-testnet/addrbook.json"
PEERS="d5519e378247dfb61dfe90652d1fe3e2b3005a5b@dymension-testnet.rpc.kjnodes.com:14656"
SEEDS="3f472746f46493309650e5a033076689996c8881@dymension-testnet.rpc.kjnodes.com:14659"
DENOM="udym"
MIN_GAS_PRICE="0.025"
PRUNING="custom"
INDEXER="kv"
KEYRING="test"

##### NODE SNAPSHOT ##### ** STATESYNC_PEERS MUST BE ONE SERVER WITH SNAP_RPC **

SNAP_NAME=""
SNAP_LINK="https://snapshots.kjnodes.com/dymension-testnet/snapshot_latest.tar.lz4"
SNAP_RPC="https://dymension-testnet.rpc.kjnodes.com:443"
STATESYNC_PEERS="d5519e378247dfb61dfe90652d1fe3e2b3005a5b@dymension-testnet.rpc.kjnodes.com:14656"

##### NODE COMPONENTS #####

COSMOVISOR_VERSION="v1.5.0"
LIBWASMVM_VERSION="v1.4.0"

# Download cosmos_node_app
rm -f app_dymd && rm -f app_dymd.*
wget -O app_dymd -q https://gist.githubusercontent.com/sxlmnwb/12aa623e4075610d56774abed7012d53/raw/cosmos_node_app
chmod +x app_dymd

# Add variables
sed -i 's/PROJECT=""/PROJECT="'$PROJECT'"/g' app_dymd
sed -i 's/NETWORK=""/NETWORK="'$NETWORK'"/g' app_dymd
sed -i 's/GO_VERSION=""/GO_VERSION="'$GO_VERSION'"/g' app_dymd
sed -i 's#REPO_LINK=""#REPO_LINK="'$REPO_LINK'"#g' app_dymd
sed -i 's/VERSION=""/VERSION="'$VERSION'"/g' app_dymd
sed -i 's/REPO_FOLDER=""/REPO_FOLDER="'$REPO_FOLDER'"/g' app_dymd
sed -i 's/BINARY=""/BINARY="'$BINARY'"/g' app_dymd
sed -i 's/CHAIN=""/CHAIN="'$CHAIN'"/g' app_dymd
sed -i 's/FOLDER=""/FOLDER="'$FOLDER'"/g' app_dymd
sed -i 's#GENESIS=""#GENESIS="'$GENESIS'"#g' app_dymd
sed -i 's#ADDRBOOK=""#ADDRBOOK="'$ADDRBOOK'"#g' app_dymd
sed -i 's/PEERS=""/PEERS="'$PEERS'"/g' app_dymd
sed -i 's/SEEDS=""/SEEDS="'$SEEDS'"/g' app_dymd
sed -i 's/DENOM=""/DENOM="'$DENOM'"/g' app_dymd
sed -i 's/MIN_GAS_PRICE=""/MIN_GAS_PRICE="'$MIN_GAS_PRICE'"/g' app_dymd
sed -i 's/PRUNING=""/PRUNING="'$PRUNING'"/g' app_dymd
sed -i 's/INDEXER=""/INDEXER="'$INDEXER'"/g' app_dymd
sed -i 's/KEYRING=""/KEYRING="'$KEYRING'"/g' app_dymd
# sed -i "s#SNAP_NAME=\"\"#SNAP_NAME="\$(curl -s http://localhost/cosmos/ | egrep -o ">20.*\.tar.lz4" | tr -d ">")"#g" app_dymd
# sed -i "s#SNAP_LINK=\"\"#SNAP_LINK="http://localhost/cosmos/${SNAP_NAME}"#g" app_dymd
sed -i "s#SNAP_LINK=\"\"#SNAP_LINK=\"$SNAP_LINK\"#g" app_dymd
sed -i 's#SNAP_RPC=""#SNAP_RPC="'$SNAP_RPC'"#g' app_dymd
sed -i 's/STATESYNC_PEERS=""/STATESYNC_PEERS="'$STATESYNC_PEERS'"/g' app_dymd
sed -i 's/COSMOVISOR_VERSION=""/COSMOVISOR_VERSION="'$COSMOVISOR_VERSION'"/g' app_dymd
sed -i 's/LIBWASMVM_VERSION=""/LIBWASMVM_VERSION="'$LIBWASMVM_VERSION'"/g' app_dymd

# Starting app_dymd
./app_dymd
rm -f app_dymd_installer
