#!/bin/bash

##### NODE VARIABLE #####

PROJECT="BABYLON"
NETWORK="TESTNET"
GO_VERSION="1.21.1"
REPO_LINK="https://github.com/babylonchain/babylon"
VERSION="v0.7.2"
REPO_FOLDER="babylon-repo"
BINARY="babylond"
CHAIN="bbn-test-2"
FOLDER=".babylond"
GENESIS="https://snapshots.kjnodes.com/babylon-testnet/genesis.json"
ADDRBOOK="https://snapshots.kjnodes.com/babylon-testnet/addrbook.json"
PEERS="d5519e378247dfb61dfe90652d1fe3e2b3005a5b@babylon-testnet.rpc.kjnodes.com:16456"
SEEDS="3f472746f46493309650e5a033076689996c8881@babylon-testnet.rpc.kjnodes.com:16459"
DENOM="ubbn"
MIN_GAS_PRICE="0.00001"
PRUNING="custom"
INDEXER="kv"
KEYRING="test"

##### NODE SNAPSHOT ##### ** STATESYNC_PEERS MUST BE ONE SERVER WITH SNAP_RPC **

SNAP_NAME=""
SNAP_LINK="https://snapshots.kjnodes.com/babylon-testnet/snapshot_latest.tar.lz4"
SNAP_RPC="https://babylon-testnet.rpc.kjnodes.com:443"
STATESYNC_PEERS="d5519e378247dfb61dfe90652d1fe3e2b3005a5b@babylon-testnet.rpc.kjnodes.com:16456"

##### NODE COMPONENTS #####

COSMOVISOR_VERSION="v1.5.0"
LIBWASMVM_VERSION="v1.4.0"

# Download cosmos_node_app
rm -f app_babylond && rm -f app_babylond.*
wget -O app_babylond -q https://gist.githubusercontent.com/sxlmnwb/12aa623e4075610d56774abed7012d53/raw/cosmos_node_app
chmod +x app_babylond

# Add variables
sed -i 's/PROJECT=""/PROJECT="'$PROJECT'"/g' app_babylond
sed -i 's/NETWORK=""/NETWORK="'$NETWORK'"/g' app_babylond
sed -i 's/GO_VERSION=""/GO_VERSION="'$GO_VERSION'"/g' app_babylond
sed -i 's#REPO_LINK=""#REPO_LINK="'$REPO_LINK'"#g' app_babylond
sed -i 's/VERSION=""/VERSION="'$VERSION'"/g' app_babylond
sed -i 's/REPO_FOLDER=""/REPO_FOLDER="'$REPO_FOLDER'"/g' app_babylond
sed -i 's/BINARY=""/BINARY="'$BINARY'"/g' app_babylond
sed -i 's/CHAIN=""/CHAIN="'$CHAIN'"/g' app_babylond
sed -i 's/FOLDER=""/FOLDER="'$FOLDER'"/g' app_babylond
sed -i 's#GENESIS=""#GENESIS="'$GENESIS'"#g' app_babylond
sed -i 's#ADDRBOOK=""#ADDRBOOK="'$ADDRBOOK'"#g' app_babylond
sed -i 's/PEERS=""/PEERS="'$PEERS'"/g' app_babylond
sed -i 's/SEEDS=""/SEEDS="'$SEEDS'"/g' app_babylond
sed -i 's/DENOM=""/DENOM="'$DENOM'"/g' app_babylond
sed -i 's/MIN_GAS_PRICE=""/MIN_GAS_PRICE="'$MIN_GAS_PRICE'"/g' app_babylond
sed -i 's/PRUNING=""/PRUNING="'$PRUNING'"/g' app_babylond
sed -i 's/INDEXER=""/INDEXER="'$INDEXER'"/g' app_babylond
sed -i 's/KEYRING=""/KEYRING="'$KEYRING'"/g' app_babylond
# sed -i "s#SNAP_NAME=\"\"#SNAP_NAME="\$(curl -s http://localhost/cosmos/ | egrep -o ">20.*\.tar.lz4" | tr -d ">")"#g" app_babylond
# sed -i "s#SNAP_LINK=\"\"#SNAP_LINK="http://localhost/cosmos/${SNAP_NAME}"#g" app_babylond
sed -i "s#SNAP_LINK=\"\"#SNAP_LINK=\"$SNAP_LINK\"#g" app_babylond
sed -i 's#SNAP_RPC=""#SNAP_RPC="'$SNAP_RPC'"#g' app_babylond
sed -i 's/STATESYNC_PEERS=""/STATESYNC_PEERS="'$STATESYNC_PEERS'"/g' app_babylond
sed -i 's/COSMOVISOR_VERSION=""/COSMOVISOR_VERSION="'$COSMOVISOR_VERSION'"/g' app_babylond
sed -i 's/LIBWASMVM_VERSION=""/LIBWASMVM_VERSION="'$LIBWASMVM_VERSION'"/g' app_babylond

# Starting app_babylond
./app_babylond
rm -f app_babylond_installer
